# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HfjaFn0lPOnq0c_-ZgoaGVJD2HbQgEfH
"""

class Network():
    def __init__(self, *args, **kwargs):
        pass

    def forward(self):
        pass

    def backward(self, grad, lr):
        pass

class Module():
    def __init__(self):
        pass

    def forward(self, x):
        pass

    def backward(self, grad, lr):
        pass