# -*- coding: utf-8 -*-
"""csv_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Afew-DQTva1Omo0tw598fQbxKdXsVvYr
"""

# Data file

